---
name: pablo-installer
steps:
  - step: bootstrap
    options:
      suite: bookworm
      target: rootfs.tar.gz
      setup-hooks:
        - 'sync-in overlay/debian/ /'
      customize-hooks:
        - echo 'root:root' | chroot "$1" chpasswd
        - systemctl enable --root="$1" systemd-networkd
        - chroot $1 echo "localhost" > $1/etc/hostnam
      packages: !include manifests/software.yaml
